apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-controller
  labels:
    app: nginx-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-controller
  template:
    metadata:
      labels:
        app: nginx-controller
    spec:
      containers:
      - name: nginx-controller
        image: rishantagarwal/nginx-rate-limiting-testing:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
